# Generated by Django 4.0 on 2023-02-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'orders'},
        ),
    ]
