# Generated by Django 4.0 on 2023-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snr', '0003_alter_order_options_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='countries',
            new_name='country',
        ),
    ]
