# Generated by Django 4.0 on 2023-03-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snr', '0005_alter_checkout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snr.checkout'),
            preserve_default=False,
        ),
    ]
