# Generated by Django 4.0 on 2023-03-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snr', '0008_order_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
    ]
